name: Amulet Titan
format: Modern
meta_share: 0.037

mainboard:
  # Creatures (9)
  - {quantity: 4, name: "Arboreal Grazer"}
  - {quantity: 4, name: "Primeval Titan"}
  - {quantity: 1, name: "Aftermath Analyst"}
  # Spells (12)
  - {quantity: 4, name: "Malevolent Rumble"}
  - {quantity: 3, name: "Scapeshift"}
  - {quantity: 3, name: "Green Sun's Zenith"}
  - {quantity: 2, name: "Summoner's Pact"}
  # Artifacts (4)
  - {quantity: 4, name: "Amulet of Vigor"}
  # Enchantments (4)
  - {quantity: 4, name: "Spelunking"}
  # Lands (31)
  - {quantity: 4, name: "Gruul Turf"}
  - {quantity: 4, name: "Forest"}
  - {quantity: 4, name: "Urza's Saga"}
  - {quantity: 4, name: "Crumbling Vestige"}
  - {quantity: 3, name: "Boseiju, Who Endures"}
  - {quantity: 2, name: "Simic Growth Chamber"}
  - {quantity: 2, name: "Lotus Field"}
  - {quantity: 1, name: "Echoing Deeps"}
  - {quantity: 1, name: "Otawara, Soaring City"}
  - {quantity: 1, name: "Tolaria West"}
  - {quantity: 1, name: "Urza's Cave"}
  - {quantity: 1, name: "Shifting Woodland"}
  - {quantity: 1, name: "Hanweir Battlements"}
  - {quantity: 1, name: "Mirrorpool"}
  - {quantity: 1, name: "Vesuva"}

sideboard:
  - {quantity: 3, name: "Dismember"}
  - {quantity: 2, name: "Soulless Jailer"}
  - {quantity: 2, name: "Firespout"}
  - {quantity: 2, name: "Vexing Bauble"}
  - {quantity: 2, name: "Force of Vigor"}
  - {quantity: 1, name: "Six"}
  - {quantity: 1, name: "Bojuka Bog"}
  - {quantity: 1, name: "Elder Gargaroth"}
  - {quantity: 1, name: "Boseiju, Who Endures"}
